### PR TITLE
Format: Run `mix format` using Elixirs new formatter

### PR DESCRIPTION
**Pull request by Zeeker**
This PR is very simple. It runs `mix format` in the root of the repository which applies the formatting of the new Elixir formatter based on the rules specified in `.formatter.ex`.

We should use this PR to take a look at the formatting and decide if there are any things we would like to tweak.

---

Running `mix format` resulted in the following change in the `credo` output:

### Before

```
1249 mods/funs, found 6 consistency issues, 2 warnings, 14 refactoring opportunities, 4 code readability issues.
```

### After

```
1249 mods/funs, found 2 warnings, 14 refactoring opportunities, 1 code readability issue.
```

### CODE REVIEW

**Comment by antonmi** [comment]
Hi, @Zeeker !
Thanks for PR!
Please resolve conflicts and be sure tests are passed.
Thank you!

**Comment by Zeeker** [comment]
Hey @antonmi, I definitely want to but I moved this weekend so as you can imagine I'm super busy atm. :)

**Comment by antonmi** [comment]
No rush)

**Comment by Zeeker** [comment]
I would love to include `mix format --check-formatted` into the Travis build, to ensure new contributions are formatted. But I'm not sure how to do that, since it's obviously only possible in elixir version 1.6.0 and above.

**Comment by Zeeker** [comment]
Btw, the tests are running now :)

**Comment by antonmi** [comment]
Thanks, @Zeeker !
It’s huge!

**Pull request merged**
