### PR TITLE
Start every test in a new process, watch for it's death

### LINKED ISSUE #283: Make test runner survive after process death
Hi Anton, thanks for the great package! 

There are a lot of possible reasons when the running process might die, when a linked process died, for example. 

Unfortunately, the test runner doesn't survive and exits immediately. It becomes very annoying because you don't know what exactly test failed and caused the death of a whole test suite. Also, there is no way (or I'm blind) to switch for detailed reports instead of regular dots.

To reproduce you can try this:

      it do: spawn_link fn -> raise "kill" end

In practice, when Ecto raises exception about the ownership, the whole suite fails and there is no way to understand what test caused the problem.

I can try to make a PR, but want to hear from you first. Thanks

### PR DESCRIPTION
**Pull request by Kukunin**
Fixes #283, where the whole suite might crash on a single test

### CODE REVIEW

**Comment by Kukunin** [comment]
Wait with merging, I'm testing it on my pet project, and I might add more commits

**Comment by Kukunin** [comment]
I checked with ex_unit - they are fault tolerant to process exits as well as they run every example in a separate PID. I'm not sure whether my change affects Ecto.Sandbox, since even `async: false` examples run in different PIDs.

**Comment by Kukunin** [comment]
I roll enough this PR with my project and can't see any downside:
- ecto isn't sensitive for this change
- it handles when a test dies well

Please, review it and merge, if you like it

**Comment by antonmi** [comment]
Thanks @Kukunin !
It looks awesome!
Sorry for late response.

**Comment by antonmi** [comment]
@Kukunin , I've just published 1.6.4 with the changes.

**Pull request merged**
