### PR TITLE
Fix: let_overridable does not cache properly

### PR DESCRIPTION
**Pull request by Zeeker**
This implements failing tests for the issue #261

### CODE REVIEW

**Comment by antonmi** [comment]
Hi, @Zeeker !
It seems to be broken.

**Comment by Zeeker** [comment]
This PR just adds failing tests for the linked issue. I don't have time to look into this but thought that these tests might help anyone who want to take a shot at this. :relaxed:

**Comment by antonmi** [comment]
Ah!) Ok

**Comment by antonmi** [comment]
Hi, @Zeeker !
Thanks for that!
I've just copied and pasted your specs to this PR
https://github.com/antonmi/espec/pull/267
So, I close this one.

**Pull request closed without merging**
